import type {
  LearnerProfile,
  CuratedResource,
  AgenticIntervention,
  RoadmapStage,
  CognitiveMetrics,
  MemoryVector,
  VisualizerConcept,
  WeeklyInsights,
  LearnerPreferences,
  AIKnowsFact,
  TodayMission,
  AICoachMessage,
  LearningConsistency,
  GoalPlannerData,
  FutureMilestone,
  Opportunity,
  Achievement,
} from "./types";

export const initialProfile: LearnerProfile = {
  name: "Sparsh",
  avatarUrl: "https://media.istockphoto.com/id/1791833349/photo/student-university-and-portrait-of-black-woman-in-library-for-learning-education-and-reading.jpg?s=612x612&w=0&k=20&c=itaBSNJVOXsvG0POV3cTlyVIi9FbzC9YGdwcNsFf914=",
  currentRole: "Builder & Curious Mind",
  aspirationalIdentity: "Multi-Disciplinary Founder, Communicator & Systems Thinker",
  humanPotentialScore: 74,
  humanPotentialBreakdown: {
    taskCompletion: 82,
    consistency: 78,
    appliedPractice: 71,
    reflectionQuality: 65,
    balancedGrowth: 58,
    noveltyLearning: 80,
    passivePenalty: 14,
    total: 74,
  },
  mindfulConsumptionRate: 86,
  weeklyFocusHours: 12.4,
  dopamineTrapsBlocked: 37,
  activeStreakDays: 14,
  currentMilestone: "Completing Public Speaking Practice Module",
  curatorStatus: "Active Curation",
  overallRoadmapProgress: 41,
};

export const initialTodayMission: TodayMission = {
  taskTitle: "12-Min Negotiation Tactics — Master Your Next High-Stakes Conversation",
  taskType: "Podcast",
  estimatedMinutes: 12,
  reward: "Unlock Communication Mastery Badge",
  nextMilestone: "Influence & Leadership Stage",
  progressPercent: 41,
  route: "/opportunities",
};

export const initialAICoach: AICoachMessage = {
  message: "Your identity vector shows a strong aspiration toward leadership and communication — but your practice time on Public Speaking has dropped 60% this week. The curator detected you spent 3 hours on passive YouTube shorts instead. Today is the perfect moment to recalibrate.",
  focusTopic: "Public Speaking & Confident Communication",
  tip: "Record yourself speaking for 2 minutes on any topic. Watching it back builds metacognitive awareness faster than any lecture.",
  energyLevel: "High",
};

export const initialLearningConsistency: LearningConsistency = {
  currentStreak: 14,
  weeklyHours: 12.4,
  weeklyConsistencyPercent: 78,
  bestStreak: 21,
  dailyGoalMet: [true, true, false, true, true, false, true],
};

export const initialGoalPlanner: GoalPlannerData = {
  careerGoal: "Launch a mission-driven venture at the intersection of AI and human growth",
  targetDate: "June 2027",
  weeklyStudyHours: 14,
  progressPercent: 41,
  milestones: [
    { label: "Map my identity, values and aspirational self", done: true },
    { label: "Build communication and leadership skills", done: false },
    { label: "Launch a side project that applies my skills", done: false },
    { label: "Grow an audience and mentor others", done: false },
  ],
};

export const initialIntervention: AgenticIntervention = {
  id: "int-101",
  type: "passive_trap",
  title: "Passive Consumption Trap Detected",
  topic: "Public Speaking & Communication",
  problemSummary: "The curator detected 3.2 hours of passive short-form video consumption in the last 2 days — content that does not map to any node in your growth identity.",
  curatorActionTaken: "Curator blocked 4 attention-trap recommendations and surfaced 2 high-intentionality alternatives aligned to your Communication node.",
  suggestedActionText: "Start Curated Practice Session",
  actionRoute: "/roadmap",
  severity: "high",
};

export const initialResources: CuratedResource[] = [
  {
    id: "res-1",
    title: "The Science of Public Confidence — What Neuroscience Says About Stage Fright",
    type: "YouTube Video",
    category: "Communication",
    estTime: "18 mins",
    difficulty: "Beginner",
    skillGain: "Confidence frameworks, nervous system regulation before speaking",
    intentionalityScore: 96,
    reasoning: "Directly maps to your Public Speaking node (currently: Practicing). Addresses your identity goal of becoming a confident communicator.",
    buildsUpon: "Self-Awareness Foundation",
    unlocksGoal: "Communication Mastery Stage",
    actionRoute: "/roadmap",
    bookmarked: false,
  },
  {
    id: "res-2",
    title: "The Psychology of Money — Key Mental Models for Financial Independence",
    type: "Book Summary",
    category: "Financial Literacy",
    estTime: "22 mins",
    difficulty: "Beginner",
    skillGain: "Long-term wealth mindset, compounding intuition, behavioral finance",
    intentionalityScore: 91,
    reasoning: "Your Financial Literacy node has been Neglected for 12 days. This curated summary will re-activate it without time overload.",
    buildsUpon: "Goal-Setting & Delayed Gratification",
    unlocksGoal: "Financial Independence Milestone",
    bookmarked: true,
  },
  {
    id: "res-3",
    title: "Building in Public — How Founders Use Authentic Storytelling to Grow Audiences",
    type: "Article",
    category: "Personal Branding",
    estTime: "10 mins",
    difficulty: "Intermediate",
    skillGain: "Narrative construction, authentic voice, community building",
    intentionalityScore: 93,
    reasoning: "Your aspirational identity includes being a communicator and builder. This bridges both nodes.",
    buildsUpon: "Public Speaking Foundation",
    unlocksGoal: "Personal Brand Launch",
    bookmarked: false,
  },
  {
    id: "res-4",
    title: "Deep Work Protocol — The 4-Hour Focus Block Method Used by Top Performers",
    type: "Podcast",
    category: "Cognitive Performance",
    estTime: "28 mins",
    difficulty: "Intermediate",
    skillGain: "Focus architecture, distraction management, cognitive peak state design",
    intentionalityScore: 89,
    reasoning: "Curated to address your Passive Consumption Penalty (currently 14 points). Teaches structural defense against attention traps.",
    buildsUpon: "Stoic Mindset Basics",
    unlocksGoal: "Deep Work Mastery Node",
    bookmarked: false,
  },
];

export const initialRoadmapStages: RoadmapStage[] = [
  {
    id: "stage-1",
    stageNumber: 1,
    title: "Identity & Foundation",
    description: "Mapping your values, aspirations, and cognitive style. Understanding who you are and who you intend to become.",
    status: "completed",
    progressPercent: 100,
    estimatedDays: 14,
    remainingDays: 0,
    scheduleStatus: "on-track",
    skillsGained: ["Self-Awareness", "Values Clarity", "Aspirational Identity Mapping", "Goal Architecture"],
    prerequisites: [],
    careerImpact: "Foundation for every decision — career pivots, skill investments, and relationship building all flow from a clear identity.",
    items: [
      {
        id: "rm-1",
        title: "Who Am I Building Toward? — A Values & Identity Mapping Exercise",
        type: "Reflection Exercise",
        category: "Identity",
        estTime: "40 mins",
        difficulty: "Beginner",
        skillGain: "Values clarity, identity articulation",
        intentionalityScore: 99,
        reasoning: "Foundation of the entire curator system. Without a clear identity vector, curation is guesswork.",
        bookmarked: false,
      },
      {
        id: "rm-2",
        title: "Designing Your Life — Bill Burnett's Core Framework",
        type: "Book Summary",
        category: "Life Design",
        estTime: "25 mins",
        difficulty: "Beginner",
        skillGain: "Opportunity mapping, life prototyping mindset",
        intentionalityScore: 95,
        reasoning: "Enables you to treat life as a design problem with multiple valid solutions.",
        bookmarked: false,
      },
    ],
  },
  {
    id: "stage-2",
    stageNumber: 2,
    title: "Skill Portfolio Building",
    description: "Deliberately acquiring a balanced portfolio of technical, creative, social, and mindset skills.",
    status: "in-progress",
    progressPercent: 52,
    estimatedDays: 42,
    remainingDays: 20,
    scheduleStatus: "ahead",
    skillsGained: ["Public Speaking", "Financial Literacy", "AI Systems Thinking", "Deep Work", "Writing"],
    prerequisites: ["Identity Foundation Complete"],
    careerImpact: "T-shaped skill portfolio creates optionality — you become hard to replace and easy to promote, fund, or partner with.",
    items: [
      {
        id: "rm-3",
        title: "The Science of Public Confidence — Neuroscience of Stage Fright",
        type: "YouTube Video",
        category: "Communication",
        estTime: "18 mins",
        difficulty: "Beginner",
        skillGain: "Confidence frameworks, vocal authority",
        intentionalityScore: 96,
        reasoning: "Public Speaking node is in Practicing state — this accelerates the path to Applying.",
        bookmarked: false,
      },
      {
        id: "rm-4",
        title: "The Psychology of Money — Morgan Housel's Core Mental Models",
        type: "Book Summary",
        category: "Financial Literacy",
        estTime: "22 mins",
        difficulty: "Beginner",
        skillGain: "Long-term wealth mindset, compounding intuition",
        intentionalityScore: 91,
        reasoning: "Financial Literacy node has been neglected. Reactivating it prevents skill imbalance.",
        bookmarked: false,
      },
      {
        id: "rm-5",
        title: "AI Agents & Human Potential — How Agentic Systems Can Curate Your Growth",
        type: "Research Paper",
        category: "AI Systems",
        estTime: "35 mins",
        difficulty: "Intermediate",
        skillGain: "Agentic AI design, human-AI collaboration patterns",
        intentionalityScore: 98,
        reasoning: "Directly aligned with your aspirational identity as an AI-and-human-growth founder.",
        bookmarked: true,
      },
    ],
  },
  {
    id: "stage-3",
    stageNumber: 3,
    title: "Application & Creation",
    description: "Building real projects, creating tangible outputs, and testing your skills under real-world conditions.",
    status: "upcoming",
    progressPercent: 8,
    estimatedDays: 60,
    remainingDays: 60,
    scheduleStatus: "on-track",
    skillsGained: ["Shipping Products", "Storytelling", "Building in Public", "Technical Leadership"],
    prerequisites: ["Stage 2: 70% Complete", "At least 3 skill nodes in Applying or Mastering state"],
    careerImpact: "Portfolio of real outputs is the single strongest signal to employers, investors, and collaborators.",
    items: [
      {
        id: "rm-6",
        title: "Building in Public — Authentic Storytelling for Builders",
        type: "Article",
        category: "Personal Branding",
        estTime: "10 mins",
        difficulty: "Intermediate",
        skillGain: "Narrative construction, audience building",
        intentionalityScore: 93,
        reasoning: "Bridges your Communication and Technical skills into a public-facing identity.",
        bookmarked: false,
      },
    ],
  },
  {
    id: "stage-4",
    stageNumber: 4,
    title: "Influence & Legacy",
    description: "Community building, mentoring others, thought leadership, and creating impact beyond yourself.",
    status: "upcoming",
    progressPercent: 0,
    estimatedDays: 90,
    remainingDays: 90,
    scheduleStatus: "on-track",
    skillsGained: ["Community Leadership", "Mentoring", "Thought Leadership", "Systems Thinking at Scale"],
    prerequisites: ["Stage 3 Complete", "At least 1 shipped project with real users"],
    careerImpact: "Moves you from individual contributor to force multiplier — the highest form of human potential.",
    items: [],
  },
];

export const initialMetrics: CognitiveMetrics = {
  growthVelocity: 14,
  attentionToIntentRatio: 86,
  retentionRate: 79,
  fatigueIndex: 18,
  dailyFocusLogs: [
    { day: "Mon", mindfulHours: 2.2, skimmingHours: 0.6, intentionality: 86 },
    { day: "Tue", mindfulHours: 3.1, skimmingHours: 0.2, intentionality: 92 },
    { day: "Wed", mindfulHours: 1.8, skimmingHours: 0.8, intentionality: 74 },
    { day: "Thu", mindfulHours: 2.6, skimmingHours: 0.3, intentionality: 88 },
    { day: "Fri", mindfulHours: 3.0, skimmingHours: 0.1, intentionality: 95 },
    { day: "Sat", mindfulHours: 1.4, skimmingHours: 1.2, intentionality: 60 },
  ],
  skillMatrix: [
    { skill: "Public Speaking",     score: 62, target: 85, category: "Communication" },
    { skill: "Financial Literacy",  score: 38, target: 75, category: "Life Skills" },
    { skill: "AI Systems Thinking", score: 79, target: 90, category: "Technical" },
    { skill: "Deep Work & Focus",   score: 74, target: 90, category: "Mindset" },
    { skill: "Writing & Narrative", score: 55, target: 80, category: "Communication" },
    { skill: "Leadership",          score: 44, target: 80, category: "Social" },
  ],
  topicProgress: [
    {
      id: "tp-1", name: "Public Speaking", category: "Communication",
      completedPercent: 62, totalItems: 10, completedItems: 6, relatedStageId: "stage-2",
      nodeState: "Practicing", timeInvested: 8.4, confidenceLevel: 60,
      lastActive: "2026-07-31", recentlyActive: true, isIdentityLevel: true,
      dependencies: ["tp-9"],
    },
    {
      id: "tp-2", name: "Deep Work", category: "Mindset",
      completedPercent: 74, totalItems: 8, completedItems: 6, relatedStageId: "stage-2",
      nodeState: "Applying", timeInvested: 11.2, confidenceLevel: 78,
      lastActive: "2026-07-31", recentlyActive: true, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-3", name: "AI Agents", category: "Technical",
      completedPercent: 79, totalItems: 12, completedItems: 9, relatedStageId: "stage-2",
      nodeState: "Applying", timeInvested: 22.0, confidenceLevel: 82,
      lastActive: "2026-07-30", recentlyActive: true, isIdentityLevel: true,
      dependencies: ["tp-11"],
    },
    {
      id: "tp-4", name: "Financial Literacy", category: "Life Skills",
      completedPercent: 28, totalItems: 8, completedItems: 2, relatedStageId: "stage-2",
      nodeState: "Neglected", timeInvested: 1.5, confidenceLevel: 30,
      lastActive: "2026-07-19", recentlyActive: false, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-5", name: "Writing", category: "Communication",
      completedPercent: 48, totalItems: 9, completedItems: 4, relatedStageId: "stage-2",
      nodeState: "Learning", timeInvested: 5.8, confidenceLevel: 50,
      lastActive: "2026-07-29", recentlyActive: false, isIdentityLevel: false,
      dependencies: ["tp-1"],
    },
    {
      id: "tp-6", name: "Fitness", category: "Health",
      completedPercent: 55, totalItems: 6, completedItems: 3, relatedStageId: "stage-2",
      nodeState: "Practicing", timeInvested: 14.0, confidenceLevel: 58,
      lastActive: "2026-07-31", recentlyActive: true, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-7", name: "Stoicism", category: "Mindset",
      completedPercent: 88, totalItems: 6, completedItems: 5, relatedStageId: "stage-1",
      nodeState: "Mastering", timeInvested: 16.5, confidenceLevel: 90,
      lastActive: "2026-07-28", recentlyActive: false, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-8", name: "Short-Form Videos", category: "Media",
      completedPercent: 0, totalItems: 0, completedItems: 0, relatedStageId: undefined,
      nodeState: "Overconsumed", timeInvested: 31.0, confidenceLevel: 10,
      lastActive: "2026-07-31", recentlyActive: true, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-9", name: "Self-Awareness", category: "Identity",
      completedPercent: 100, totalItems: 5, completedItems: 5, relatedStageId: "stage-1",
      nodeState: "Completed", timeInvested: 9.0, confidenceLevel: 95,
      lastActive: "2026-07-20", recentlyActive: false, isIdentityLevel: true,
      dependencies: [],
    },
    {
      id: "tp-10", name: "Leadership", category: "Social",
      completedPercent: 22, totalItems: 10, completedItems: 2, relatedStageId: "stage-3",
      nodeState: "Exploring", timeInvested: 2.5, confidenceLevel: 25,
      lastActive: "2026-07-25", recentlyActive: false, isIdentityLevel: true,
      dependencies: ["tp-1", "tp-5"],
    },
    {
      id: "tp-11", name: "Python Systems", category: "Technical",
      completedPercent: 85, totalItems: 10, completedItems: 9, relatedStageId: "stage-2",
      nodeState: "Mastering", timeInvested: 28.0, confidenceLevel: 88,
      lastActive: "2026-07-30", recentlyActive: true, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-12", name: "Design Thinking", category: "Creative",
      completedPercent: 35, totalItems: 7, completedItems: 2, relatedStageId: "stage-2",
      nodeState: "Learning", timeInvested: 4.2, confidenceLevel: 38,
      lastActive: "2026-07-22", recentlyActive: false, isIdentityLevel: false,
      dependencies: [],
    },
    {
      id: "tp-13", name: "Mental Wellness", category: "Health",
      completedPercent: 60, totalItems: 6, completedItems: 4, relatedStageId: "stage-1",
      nodeState: "Applying", timeInvested: 8.0, confidenceLevel: 65,
      lastActive: "2026-07-29", recentlyActive: false, isIdentityLevel: false,
      dependencies: ["tp-2"],
    },
    {
      id: "tp-14", name: "Personal Brand", category: "Communication",
      completedPercent: 15, totalItems: 8, completedItems: 1, relatedStageId: "stage-3",
      nodeState: "Blocked", timeInvested: 1.2, confidenceLevel: 18,
      lastActive: "2026-07-10", recentlyActive: false, isIdentityLevel: true,
      dependencies: ["tp-1", "tp-5", "tp-3"],
    },
    {
      id: "tp-15", name: "Negotiation", category: "Social",
      completedPercent: 40, totalItems: 6, completedItems: 2, relatedStageId: "stage-2",
      nodeState: "Learning", timeInvested: 3.8, confidenceLevel: 42,
      lastActive: "2026-07-27", recentlyActive: false, isIdentityLevel: false,
      dependencies: ["tp-1"],
    },
  ],
};

export const initialWeeklyInsights: WeeklyInsights = {
  hoursStudied: 12.4,
  lessonsCompleted: 9,
  projectsCompleted: 1,
  consistencyPercent: 78,
  strengths: [
    { topic: "Deep Work",      score: 91, note: "4 consecutive high-intentionality focus sessions — top 10% of your history." },
    { topic: "AI Systems",     score: 85, note: "Consistently the most intentional node. Application-level thinking is evident." },
    { topic: "Stoicism",       score: 88, note: "Mastery maintained with zero passive content detected in this node." },
  ],
  weaknesses: [
    { topic: "Financial Literacy", score: 28, suggestion: "Inactive for 12 days. The curator suggests a 10-min book summary to reactivate this node before it atrophies." },
    { topic: "Personal Brand",     score: 15, suggestion: "Blocked by dependencies. Strengthen Public Speaking and Writing first to unblock this node." },
    { topic: "Leadership",         score: 22, suggestion: "Only in Exploring state. Schedule one intentional practice session this week." },
  ],
  aiSummary: "Your growth engine is firing on technical and mindset tracks, but three life-domain nodes are critically underserved — Financial Literacy, Personal Brand, and Leadership. Your Human Potential Score is being dragged down by 14 points of passive consumption penalty. The curator has intercepted 37 attention-trap recommendations this week.",
  suggestedPractice: [
    { title: "12-Min Negotiation Tactics Podcast",         type: "Podcast",          reason: "Reactivates Negotiation node — 13 days inactive.",        route: "/opportunities" },
    { title: "Psychology of Money — Key Mental Models",    type: "Book Summary",     reason: "Financial Literacy node critical. 12 days neglected.",     route: "/roadmap" },
    { title: "Record a 2-Min Impromptu Speech Practice",   type: "Reflection Exercise", reason: "Moves Public Speaking from Practicing to Applying.",     route: "/learning-lab" },
  ],
};

export const initialMemoryVectors: MemoryVector[] = [
  {
    id: "mv-1",
    category: "Identity & Aspirations",
    statement: "User's aspirational identity is a multi-disciplinary founder at the intersection of AI and human growth — not purely technical.",
    confidence: 94,
    lastUpdated: "2026-07-28",
    impactOnCurator: "Biases curation toward leadership, communication, and product-thinking content — not just code.",
    active: true,
  },
  {
    id: "mv-2",
    category: "Identity & Aspirations",
    statement: "User explicitly wants to be a confident, compelling public communicator and storyteller.",
    confidence: 91,
    lastUpdated: "2026-07-25",
    impactOnCurator: "Elevates Public Speaking, Writing, and Personal Brand nodes in the growth roadmap.",
    active: true,
  },
  {
    id: "mv-3",
    category: "Cognitive Style",
    statement: "User retains 40% more from podcast + immediate reflection pairs versus passive video watching.",
    confidence: 87,
    lastUpdated: "2026-07-30",
    impactOnCurator: "Prioritizes podcast and interactive formats. Suppresses passive long-form video.",
    active: true,
  },
  {
    id: "mv-4",
    category: "Learning Habits",
    statement: "User's best focus window is 8–11am. Afternoons show 35% drop in intentionality scores.",
    confidence: 82,
    lastUpdated: "2026-07-29",
    impactOnCurator: "Schedules hardest growth tasks in morning mission. Lighter reflection content for evenings.",
    active: true,
  },
  {
    id: "mv-5",
    category: "Curator Filters",
    statement: "User is susceptible to short-form video rabbit holes — 3+ hour passive sessions detected twice this week.",
    confidence: 96,
    lastUpdated: "2026-07-31",
    impactOnCurator: "Increases passive consumption penalty weighting. Surfaces pattern-break interventions proactively.",
    active: true,
  },
  {
    id: "mv-6",
    category: "Curator Filters",
    statement: "User finds financial content intimidating — avoidance pattern detected across 3 consecutive weeks.",
    confidence: 79,
    lastUpdated: "2026-07-20",
    impactOnCurator: "Serves Financial Literacy through narrative/story formats rather than data-heavy analyses.",
    active: true,
  },
];

export const initialPreferences: LearnerPreferences = {
  learningStyle: "Auditory",
  dailyGoalMinutes: 45,
  preferredFormat: "Mixed",
  difficultyLevel: "Intermediate",
  lastUpdated: "2026-07-28",
};

export const initialAIKnows: AIKnowsFact[] = [
  { id: "aik-1", fact: "You learn 40% faster from podcast + reflection pairs than from passive video.", category: "Cognitive Style", confidenceLevel: 87 },
  { id: "aik-2", fact: "Your peak focus window is 8–11am. Afternoons are 35% less intentional.", category: "Learning Habits", confidenceLevel: 82 },
  { id: "aik-3", fact: "You have an avoidance pattern around Financial Literacy content — 3 weeks of neglect.", category: "Behavioral Pattern", confidenceLevel: 79 },
  { id: "aik-4", fact: "Public Speaking is your highest identity-level aspiration but lowest practice time ratio.", category: "Identity Gap", confidenceLevel: 91 },
  { id: "aik-5", fact: "Your short-form video consumption is a persistent passive trap — 31 hours logged with zero growth return.", category: "Attention Pattern", confidenceLevel: 96 },
  { id: "aik-6", fact: "When you reflect in writing after a session, your 7-day retention jumps from 42% to 74%.", category: "Retention Pattern", confidenceLevel: 88 },
];

export const initialVisualizerConcepts: VisualizerConcept[] = [
  {
    id: "vc-1",
    title: "How the Curator Builds Your Identity Vector",
    concept: "Vector Embedding of Self",
    description: "Your aspirations, habits, and skills are encoded as a high-dimensional vector. The curator measures cosine similarity between your current state and your aspirational identity to find the shortest intentional path.",
    keyTakeaways: [
      "Your identity is a living vector, not a fixed label",
      "Every curated resource moves you closer or farther from your aspirational self",
      "Passive content creates 'identity drift' — moving you away from your vector",
      "The curator's job is to minimize drift and maximize directed growth velocity",
    ],
    interactiveCodeSnippet: `# Simplified identity vector similarity
import numpy as np

current_self = np.array([0.6, 0.3, 0.8, 0.2, 0.5])  
# [communication, finance, technical, leadership, creativity]

aspirational_self = np.array([0.9, 0.7, 0.85, 0.8, 0.7])

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

gap = 1 - cosine_similarity(current_self, aspirational_self)
print(f"Identity Gap Score: {gap:.3f}")
print(f"Nodes needing most attention: Finance, Leadership, Creativity")`,
    executionTrace: [
      { step: 1, title: "Load identity vectors", memoryState: "current=[0.6, 0.3, 0.8, 0.2, 0.5]", detail: "Fetched from your 90-day activity history and reflection logs." },
      { step: 2, title: "Compute cosine similarity", memoryState: "similarity=0.847", detail: "85% alignment with your aspirational self. 15% identity gap detected." },
      { step: 3, title: "Identify gap nodes", memoryState: "gaps=[finance:0.4, leadership:0.6]", detail: "Finance and Leadership nodes have the largest delta from aspiration." },
      { step: 4, title: "Curate gap-closing resources", memoryState: "curated=[podcast, book summary]", detail: "Curator surfaces 2 intentional resources targeting your gap nodes." },
    ],
    quizQuestions: [
      {
        question: "What does a high cosine similarity between your current and aspirational identity vectors mean?",
        options: ["You are far from your goals", "You are closely aligned with your aspirational self", "You need more technical skills", "Your growth has stagnated"],
        correctIndex: 1,
        explanation: "Cosine similarity measures directional alignment. High similarity means your current self closely mirrors your aspirational identity.",
      },
    ],
  },
];

export const initialFutureMilestones: FutureMilestone[] = [
  {
    period: "Now",
    skills: ["Public Speaking (Practicing)", "AI Systems (Applying)", "Deep Work (Applying)", "Stoicism (Mastering)"],
    projects: ["Identity Map Completed"],
    careerReadiness: 42,
    goalCompletion: 41,
    description: "Current state: strong technical foundation, mindset developing. Critical gaps in communication and financial literacy.",
  },
  {
    period: "3 Months",
    skills: ["Public Speaking (Applying)", "Financial Literacy (Learning)", "Leadership (Practicing)", "Writing (Applying)"],
    projects: ["First public talk or podcast appearance", "Side project launched"],
    careerReadiness: 60,
    goalCompletion: 58,
    description: "Communication skills will be deployable. Financial literacy reactivated. First tangible public outputs.",
  },
  {
    period: "6 Months",
    skills: ["Personal Brand (Building)", "Leadership (Applying)", "Negotiation (Mastering)", "Design Thinking (Applying)"],
    projects: ["Community of 100+ followers", "Revenue-generating project"],
    careerReadiness: 75,
    goalCompletion: 72,
    description: "T-shaped skill portfolio visible to the world. Influence beginning to scale.",
  },
  {
    period: "1 Year",
    skills: ["All core nodes at Applying or Mastering", "Mentoring others", "Thought Leadership"],
    projects: ["Venture launched", "Published content with 1000+ reads", "Mentored 5+ people"],
    careerReadiness: 92,
    goalCompletion: 88,
    description: "Multi-disciplinary founder profile complete. Ready to lead, invest in others, and create at scale.",
  },
];

export const initialOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    type: "Workshop",
    title: "Storytelling for Founders — 3-Day Intensive",
    organizer: "On Deck",
    deadline: "2026-08-15",
    description: "Learn how to craft compelling narratives for fundraising, hiring, and community building. Past attendees have 3x'd their audience growth.",
    relevanceScore: 97,
    tags: ["Communication", "Personal Brand", "Founders"],
    bookmarked: false,
  },
  {
    id: "opp-2",
    type: "Mentorship",
    title: "1:1 Mentorship with a Founder in AI x Education",
    organizer: "Luma Community",
    description: "Monthly 45-minute sessions with founders building at the intersection of AI and human development.",
    relevanceScore: 95,
    tags: ["AI", "Founders", "Human Potential", "Mentorship"],
    bookmarked: true,
  },
  {
    id: "opp-3",
    type: "Hackathon",
    title: "Human Potential Hack — Build for Behavioral Change",
    organizer: "Google for Startups",
    deadline: "2026-09-01",
    description: "48-hour hackathon specifically for tools that optimize human behavior and learning. Judges include investors from a16z and First Round.",
    relevanceScore: 99,
    tags: ["AI", "Human Potential", "Hackathon", "Founders"],
    bookmarked: false,
  },
  {
    id: "opp-4",
    type: "Conference",
    title: "The Long Game Summit — Annual Conference on Intentional Living",
    organizer: "The Long Game",
    deadline: "2026-08-30",
    description: "Annual gathering of people building intentional lives — speakers include authors, founders, athletes, and philosophers.",
    relevanceScore: 88,
    tags: ["Mindset", "Intentional Living", "Networking"],
    bookmarked: false,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: "ach-1",
    title: "Identity Architect",
    description: "Completed the Identity & Foundation stage of your growth roadmap.",
    icon: "Target",
    unlocked: true,
    unlockedAt: "2026-07-20",
    category: "Milestone",
    xpReward: 500,
  },
  {
    id: "ach-2",
    title: "Intentional Consumer",
    description: "Maintained a mindful consumption rate above 80% for 7 consecutive days.",
    icon: "ShieldCheck",
    unlocked: true,
    unlockedAt: "2026-07-28",
    category: "Streak",
    xpReward: 350,
  },
  {
    id: "ach-3",
    title: "14-Day Growth Streak",
    description: "Completed at least one intentional growth task every day for 14 days.",
    icon: "Flame",
    unlocked: true,
    unlockedAt: "2026-07-31",
    category: "Streak",
    xpReward: 400,
  },
  {
    id: "ach-4",
    title: "Node Activator",
    description: "Moved 3 nodes from Neglected to Learning state in a single week.",
    icon: "Zap",
    unlocked: false,
    progressCurrent: 1,
    progressTarget: 3,
    category: "Learning",
    xpReward: 450,
  },
  {
    id: "ach-5",
    title: "Balance Seeker",
    description: "Reach at least 50% progress in 5 different life-domain categories.",
    icon: "BarChart2",
    unlocked: false,
    progressCurrent: 3,
    progressTarget: 5,
    category: "Milestone",
    xpReward: 600,
  },
  {
    id: "ach-6",
    title: "Trap Breaker",
    description: "Go 7 days without a passive consumption session flagged by the curator.",
    icon: "TrendingUp",
    unlocked: false,
    progressCurrent: 3,
    progressTarget: 7,
    category: "Streak",
    xpReward: 500,
  },
];
