import React, { useEffect, useState } from "react";
import { Sparkles, Code, ArrowRight, CheckCircle2, Cpu } from "lucide-react";
import { Card } from "../components/ui/Card";
import { apiService } from "../api";
import type { VisualizerConcept } from "../api/types";

export const VisualizerPage: React.FC = () => {
  const [concepts, setConcepts] = useState<VisualizerConcept[]>([]);
  const [activeConceptIndex, setActiveConceptIndex] = useState<number>(0);
  const [activeStep, setActiveStep] = useState<number>(1);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchConcepts = async () => {
      setLoading(true);
      try {
        const data = await apiService.getVisualizerNotes();
        setConcepts(data);
      } catch (err) {
        console.error("Axios GET /api/visualizer failed", err);
      } finally {
        setLoading(false);
      }
    };
    fetchConcepts();
  }, []);

  if (loading || concepts.length === 0) {
    return (
      <div className="w-full min-h-[60vh] flex items-center justify-center">
        <p className="text-sm text-gray-700">Loading Visualizer Concept Simulations via Axios...</p>
      </div>
    );
  }

  const activeConcept = concepts[activeConceptIndex];

  return (
    <div className="w-full max-w-7xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div>
        <h1 className="text-3xl text-gray-900">
          Visualizer <span>Notes & Simulations</span>
        </h1>
        <p className="text-sm text-gray-600 mt-1 flex items-center gap-1.5">
          <Sparkles size={16} className="text-amber-600" />
          <span>Interactive simulations generated by PACER to replace passive video scrolling.</span>
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Interactive Execution Stepper (7 cols) */}
        <Card className="lg:col-span-7 space-y-5 border-white/80">
          <div className="flex items-center justify-between">
            <div>
              <span className="px-3 py-1 bg-amber-100 text-amber-900 rounded-full text-2xs uppercase tracking-wider">
                {activeConcept.concept}
              </span>
              <h2 className="text-xl text-gray-900 mt-1">{activeConcept.title}</h2>
            </div>
            <span className="text-xs text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
              Interactive Simulation
            </span>
          </div>

          <p className="text-xs text-gray-600 leading-relaxed">{activeConcept.description}</p>

          {/* Interactive Memory / Execution Trace Steps */}
          {activeConcept.executionTrace && (
            <div className="p-4 bg-zinc-900 rounded-2xl text-white space-y-3 shadow-inner">
              <div className="flex items-center justify-between text-xs text-zinc-400 border-b border-zinc-800 pb-2">
                <span className="flex items-center gap-1.5">
                  <Cpu size={14} className="text-amber-400" />
                  <span>PACER Hardware & Vector Memory Frame Stepper</span>
                </span>
                <span>Step {activeStep} of {activeConcept.executionTrace.length}</span>
              </div>

              <div className="space-y-2">
                {activeConcept.executionTrace.map((item) => {
                  const isCurrent = item.step === activeStep;
                  const isDone = item.step < activeStep;
                  return (
                    <div
                      key={item.step}
                      onClick={() => setActiveStep(item.step)}
                      className={`p-3 rounded-xl border text-xs flex items-center justify-between cursor-pointer transition-all ${
                        isCurrent
                          ? "bg-amber-400/20 border-amber-400 text-amber-200"
                          : isDone
                          ? "bg-zinc-800/50 border-zinc-700 text-zinc-400"
                          : "bg-zinc-950 border-zinc-800 text-zinc-600"
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        <span className="w-5 h-5 rounded-full bg-zinc-800 flex items-center justify-center text-2xs">
                          {item.step}
                        </span>
                        <div>
                          <p>{item.title}</p>
                          <p className="text-2xs text-zinc-400 font-sans">{item.detail}</p>
                        </div>
                      </div>
                      <span className="text-2xs font-mono bg-zinc-800 px-2 py-0.5 rounded text-amber-300">{item.memoryState}</span>
                    </div>
                  );
                })}
              </div>

              {/* Stepper Controls */}
              <div className="flex items-center justify-between pt-2">
                <button
                  disabled={activeStep <= 1}
                  onClick={() => setActiveStep((prev) => Math.max(1, prev - 1))}
                  className="px-3 py-1.5 rounded-full bg-zinc-800 text-zinc-300 text-xs disabled:opacity-40 cursor-pointer"
                >
                  Previous Step
                </button>
                <button
                  disabled={activeStep >= (activeConcept.executionTrace?.length || 4)}
                  onClick={() => setActiveStep((prev) => Math.min(activeConcept.executionTrace!.length, prev + 1))}
                  className="px-4 py-1.5 rounded-full bg-amber-400 text-amber-950 text-xs hover:bg-amber-300 transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <span>Step Forward</span>
                  <ArrowRight size={14} />
                </button>
              </div>
            </div>
          )}

          {/* Key Takeaways */}
          <div className="space-y-2 pt-2">
            <h3 className="text-xs text-gray-900 uppercase tracking-wider">Key Insights</h3>
            {activeConcept.keyTakeaways.map((takeaway, idx) => (
              <div key={idx} className="flex items-start gap-2 text-xs text-gray-700">
                <CheckCircle2 size={14} className="text-emerald-600 shrink-0 mt-0.5" />
                <span>{takeaway}</span>
              </div>
            ))}
          </div>
        </Card>

        {/* Right Code Snippet & Notes Library (5 cols) */}
        <div className="lg:col-span-5 space-y-5">
          <Card dark className="space-y-3 font-mono">
            <div className="flex items-center justify-between text-xs text-zinc-400 border-b border-zinc-800 pb-2">
              <span className="flex items-center gap-1.5 text-amber-400 font-sans">
                <Code size={16} />
                <span>Dry-Run Python Sandbox</span>
              </span>
              <span className="text-2xs">Python 3.12</span>
            </div>

            <pre className="text-xs text-emerald-300 leading-relaxed overflow-x-auto p-2 bg-zinc-950/80 rounded-xl">
              {activeConcept.interactiveCodeSnippet}
            </pre>
          </Card>

          {/* Concepts Switcher Library */}
          <Card className="space-y-3">
            <h3 className="text-sm text-gray-900">Visual Notes & Simulation Library</h3>

            {concepts.map((concept, idx) => (
              <div
                key={concept.id}
                onClick={() => {
                  setActiveConceptIndex(idx);
                  setActiveStep(1);
                }}
                className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
                  activeConceptIndex === idx
                    ? "bg-amber-50 border-amber-300 shadow-sm"
                    : "bg-white/60 border-gray-200/80 hover:border-black/20"
                }`}
              >
                <div className="flex items-center justify-between">
                  <h4 className="text-xs text-gray-900">{concept.title}</h4>
                  <span className="text-2xs bg-amber-100 text-amber-900 px-2 py-0.5 rounded-full">
                    {concept.concept}
                  </span>
                </div>
                <p className="text-2xs text-gray-500 mt-1 line-clamp-2">{concept.description}</p>
              </div>
            ))}
          </Card>
        </div>

      </div>
    </div>
  );
};
